# -*- coding: utf-8 -*-

"""
/***************************************************************************
 FundoValeMeta
                                 A QGIS plugin
 plugin used in the Meta Florestal 2030 project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
    begin                : 2021-12-15
    copyright            : (C) 2021 by Herbert Lincon R. A. Santos / Imaflora
    email                : herbert.santos@imaflora.org
 ***************************************************************************/
"""

__author__ = 'Herbert Lincon R. A. Santos / Imaflora'
__date__ = '2021-12-15'
__copyright__ = '(C) 2021 by Herbert Lincon R. A. Santos / Imaflora'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """
    Load fvaleMetaPlugin class from file fvale_mflorestal_main.
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .fvale_mflorestal_main import fvaleMetaPlugin
    return fvaleMetaPlugin()
