# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Sistema de Validação de Polígonos (SVP) Compromisso Florestal

                                 A QGIS plugin

 plugin used in the Compromisso Florestal project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
    begin                : 2022-01-15
    copyright            : (C) 2022 by Herbert Lincon R. A. Santos / Imaflora
    email                : herbert.santos@imaflora.org
 ***************************************************************************/
"""

__author__ = 'Herbert Lincon R. A. Santos / Imaflora'
__date__ = '2022-01-15'
__copyright__ = '(C) 2022 by Herbert Lincon R. A. Santos / Imaflora'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """
    Load fvaleMetaPlugin class from file fvale_mflorestal_main.
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .fvale_mflorestal_main import fvaleMetaPlugin
    return fvaleMetaPlugin()
